[general]
enabled=yes
pretty=yes

[voice-guard]
type=user
read_only=no
password=voice-guard-secret
; ARI url: http://asterisk:8088/ari
; Python will connect to http://asterisk:8088/ari or http://localhost:8088/ari
password_format=plain
